service: rent-mailer

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless-admin
  region: us-east-1
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:dynamodb:*:*:table/"
            - Ref: GmailApiTokensTable

functions:
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
          cors: true

  tokens:
    handler: handler.tokens
    events:
      - http:
          path: tokens
          method: get
          cors: true

resources:
  Resources:
    GmailApiTokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: GmailApiTokens
        AttributeDefinitions:
          - AttributeName: ClientId
            AttributeType: S
        KeySchema:
          - AttributeName: ClientId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

package:
  exclude:
    - serverless.yml
    - package.json
    - package-lock.json
    - LICENSE
